import spacy

glove = spacy.load('en_core_web_md')

doc1 = '''
Title: Sentiment analysis on social media for stock movement prediction
Author: ThienHaiNguyen
The goal of this research is to build a model to predict stock price movement using the sentiment from social media. Unlike previous approaches where the overall moods or sentiments are considered, the sentiments of the specific topics of the company are incorporated into the stock prediction model. Topics and related sentiments are automatically extracted from the texts in a message board by using our proposed method as well as existing topic models. In addition, this paper shows an evaluation of the effectiveness of the sentiment analysis in the stock prediction task via a large scale experiment. Comparing the accuracy average over 18 stocks in one year transaction, our method achieved 2.07% better performance than the model using historical prices only. Furthermore, when comparing the methods only for the stocks that are difficult to predict, our method achieved 9.83% better accuracy than historical price method, and 3.03% better 1.2 than human sentiment method.
The results of accuracy measure are shown in Table 6. In addition to the result of each stock, we also calculated the average of 18 stocks for each model for easy comparison. Using Aspect-based sentiment feature achieved the best result with 54.41% average accuracy for 18 stocks. As discussed in Section 2, degrees of accuracy of 56% hit rate are often reported as satisfying results for stock prediction. In addi- tion, the number of instances (transaction dates) in test set of most of other researches is small, and the number of stock is usually only one. In contrast, the advantage of this work is that we used the training and test data on a long period (one year) containing many instances, and for many stocks (18 stocks). For some stocks, the accuracies are quite high, such as 71.05% for AMZN stock, 64.47% for DELL stock and so on.
To assess the effectiveness of integrating mood information, we compare our Aspect-based sentiment method with the Price only method. The results show that the model using mood information outperforms 2.07% on the average accuracy than the model without mood. Furthermore, comparing the Human sentiment with Price only method, it indicated that the prediction accuracy is improved 1.91% by using the sentiments annotated by human. Therefore, we can conclude that integration of the sentiments of both overall documents and specific topics from social media could help to improve the stock market prediction. To assess the effectiveness of automatic sentiment analysis and human sentiment, we compare our Aspect-based sentiment method with the Human sentiment method. The results show that our auto- matically extracted sentiment is slightly higher than using the sentiment annotated by human. Therefore, our method is comparable to the human sentiment method. Note that the advantage of our method is that it can be applicable for other social media without human an- notated sentiment such as the Twitter.
The Aspect-based sentiment method outperformed over 2.54%, 2.14% and 2.87% on average accuracy compared to Sentiment classification, LDA-based method and JST-based method, respectively. The LDA-based and JST-based method seem to be not successful in this experiment. The limitation of these methods is that we have to specify the number of hidden topics in LDA and the number of hidden topics and sentiments in JST. In our experiment, we
specify 50 topics for all of the stock. This assumption would be not appropriate in gen- eral. For the individual stock, the number of discussed topics depends on the content of the messages. Therefore, the appropriate number of hidden topics may be varied for different stocks. However, there is no way to determine the number of topics in the model of LDA and JST. One of the solutions is a grid search trying different number of top- ics and finding the best value. However, since the running time of the Gibbs Sampling depends on the size of the dataset, it takes very long time to run it repeatedly on a big dataset of 18 stocks for a long period. Therefore, a grid search cannot be tested in our experiment.
To assess the effectiveness of topic-sentiment feature, we compare our Aspect-based sentiment method with Sentiment classification method (using only sentiment information) and LDA- based method (using only topic information). The results indicate that using topic-sentiment feature is better than using only senti- ments by 2.54% accuracy, and using only topics by 2.14% accuracy. Therefore, understanding on which topics the sentiments are ex- pressed is useful for stock market prediction. In other words, the topic-sentiment feature is better than only topic or sentiment feature. Although the sentiment information is effective for the stock pre- diction on average, in the comparison on the individual stocks, the model with sentiment analysis is worse than the price only model for several stocks. There are many possible reasons for it. As discussed in Section 2, the stock market is influenced by many factors. Some proposed that they are not predictable with more than 50% accuracy. One reason is that the sentiment might not be a factor which causes the stock price moving. Another reason is that even though sentiment might be one of the factors which affect price moving, the extracted sentiments from the Message Boards do not reflect the price because of the messy, fault comment or fault prediction of human when they post the messages.
A simple assumption about the effectiveness of sentiment feature is that the sentiment analysis may not provide any additional information if the stock movement can be predicted well by the historical price only. If the accuracy of the price only model is high, there are trends and historical repetition in the stock. In such cases, only historical prices might be enough to predict, and integration of the sentiment may not improve the accuracy much. On the other hand, if the accuracy of the price only model is low, the stock seems to have no pattern in its history. For such stocks, the use of sentiment may be effective for the prediction.
To investigate the above assumption, we compare the models from another point of view. First, we define a threshold α. If the accuracy of the stock in the Price only method (APriceOnly) is higher than α, this stock is discarded from the evaluation. In other words, we compared the average accuracy for the stocks where APriceOnly shows the average accuracies against various thresholds. It is found that the difference between the models with and without sentiment information becomes greater when α is set smaller. At the threshold 50%, using our Aspect-based sentiment model improved the accuracy over 9.83% compared to Price only, over 3.03% compared to Human sentiment method. In addition, in most of the thresholds, our method achieved the best accuracy compared with other methods.
Stock price prediction is a challenging task because the stock prices are affected by many factors. This paper presents the novel method to integrate the sentiments in social media for the predic- tion of stock price movement. The contribution of this study can be summarized as follows. First, while the overall sentiments in the doc- uments are considered in the previous research, this research pro- posed a method using the sentiment of the topic for stock market prediction. Second, we proposed two methods to capture these topic sentiment associations. One is JST-based method that relies on the existing topic model, the other is Aspect-based sentiment method where the topics and sentiments are identified by the proposed method. Finally, this is the first research to show the effectiveness of incorporation of the sentiment analysis by investigation on a large scale test data. From a practical point of view, although the average accuracy is only 54.41%, the proposed method can predict the stock price movement with more than 60% accuracy for a few stocks, and performs much better than other methods for the stocks that are difficult to predict with only past prices.
A limitation of this research is that we specified the number of topics and sentiment beforehand for the LDA and JST-based method. To overcome this weakness, a non-parametric topic model that can infer the number of topics and sentiments automatically is useful to extract the topic and sentiment simultaneously for the stock prediction. This will be done in our future work. The current model only predicts if the stock price is up or down. However, people may want to forecast drastic movement of the stock market. In that sense, the proposed model is insufficient. However, our model can be extended to predict the degree of the change by setting more fine grained classes such as 'great up', 'little up', 'little down', 'great down' and so on.
One of the weaknesses of our method is that only the historical prices and sentiments derived from social media are considered. In future, we will try to find and integrate more factors which can affect the stock prices to develop a more accurate stock prediction model. For example, co-variance between stocks, macroeconomic indicators and the financial conditions of the company, which can be guessed from the income statement, balance sheet and cash flow, are important factors to be considered in the stock prediction model.'''

# Actual Summary of the doc
# doc2 = '''
# The goal of this research is to build a model to predict stock price movement using the                sentiment from social media. Topics and related sentiments are automatically extracted from the texts in a message board by using our proposed method as well as existing topic models. Comparing the accuracy average over 18 stocks in one year transaction, our method achieved 2.07% better performance than the model using historical prices only. The LDA -based and JST -based method seem to be not successful in this imetersexperiment. However, there is no way to determine the number of topics in the model of the JST and LDA. One possibility is to search a grid of the solutions of the LDA and J ST to find the best solution for each topic. The results of accuracy measure are shown in Table 6. Using Aspect -centricbased sentiment feature achieved the best result with 54.41% average accuracy for 18 stocks. For some stocks, the accuracies are quite high, such as 71.05% for AMZN stock, 64.47% for DELL stock and so on. For all of the topics we specify in the experiment we specify the appropriate stock appropriate for all of them. For individual stock, the. number of discussed topics depends on the content of the messages. The number of hidden topics may be varied for different stocks, since the size of the dataset depends on. the time of the running time. We can conclude that integ ration of the sentiments of both overall documents and speciﬁc viewpoints from social. media could help to improve the stock market prediction.'''


# Summary of another doc
# doc2 = '''
# Sentiment analysis is an important current research area. This paper shows that a hybrid classification can improve the classification effectiveness in terms of micro - and macro -averaged F1. Sentiment analysis provides companies with a means to estimate the extent of product acceptance and to determine strategies to improve product quality. It also facilitates policy makers or politicians to analyse public sentiments with respect to policies, public services or political issues. The results indicate that the SBC improved the effectiveness of hybrid classification, especially the hybrid configuration in which the S BC a nd SVM were applied. The SBC was not applied for the sample set 1 to avoid ethical issues, i.e., hitting grotesquesearch engines with a significant amount of queries (= 8,510,880 queries), and to save time for the Closeness Measurer to collect the hit counts required. Surprisingly, the results clearly showthat the search engine used did affect each grotesquecloseness measure. The best results were produced by the RIPPER set using ID3 and the best set by RIPPERs using ID4 and ID5. The third and fourth data sets, the log likelihood ratio performed better than the three sample sets for all the three closeness measures for Yahoo! and Google, however,. In our experimental setting, our SBC used the Google hit count and the loglihood ratio was better than that of Yahoo! For the second sample set, however, we used the ID3 rule set and the rule set was more aggressive than the ID4 rule set.
# '''

# doc2 = '''
# Sentiment analysis of news articles is different from that of other text types. We identified three subtasks that need to be addressed: defin ition of the target, separation of the good and bad news content and analysis of clearly marked opinion. The experiments conducted used different windows around the mentions of the target, by computing a score of the score on words that were at the same time opinion words and category words. We tested whether or not subject doma in-defining words should be ignored. Results showed that this idea is more appropriate in the context of news opinion mining and that the approaches taking this into consideration produce a better performance. We used WordNet Affect (Strapparava and Valitutti, 2004), SentiWordNet (Esuli and Sebastiani, 2006), MicroWNOp (Cerini et al, 2007) and an in-house built resource of opinion words with associated polarity, which we denote by JRC Tonality. As it can be seen, the different lexicons performed dramatically in removing the impact of some words was significant for some resources or none for others. The results can see from the difference in the whole process applied to the opinion mining process to the whole of the news industry can be shown in the table below. The table also shows the results obtained using different window sizes and eliminating words that coincided with the respective words in the respective lexicon, as well as the number of quotes that were correctly classified as positive or negative.
# '''

doc2 = '''
In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before final copy is available. It is also used to temporarily replace text in a process called greeking, which allows designers to consider the form of a webpage or publication, without the meaning of the text influencing the design.

Lorem ipsum is typically a corrupted version of De finibus bonorum et malorum, a 1st-century BC text by the Roman statesman and philosopher Cicero, with words altered, added, and removed to make it nonsensical and improper Latin. The first two words themselves are a truncation of 'dolorem ipsum' ('pain itself').

Versions of the Lorem ipsum text have been used in typesetting at least since the 1960s, when it was popularized by advertisements for Letraset transfer sheets.[1] Lorem ipsum was introduced to the digital world in the mid-1980s, when Aldus employed it in graphic and word-processing templates for its desktop publishing program PageMaker. Other popular word processors, including Pages and Microsoft Word, have since adopted Lorem ipsum,[2] as have many LaTeX packages,[3][4][5] web content managers such as Joomla! and WordPress, and CSS libraries such as Semantic UI.'''

em_doc1 = glove(doc1)
em_doc2 = glove(doc2)

similarity_score = em_doc1.similarity(em_doc2)
print("Similarity: ",similarity_score)