from dotenv import load_dotenv
from langchain.chat_models import ChatOpenAI
from langchain.schema import (SystemMessage, HumanMessage)
# from langchain.llms import OpenAI
# from langchain import HuggingFaceHub

load_dotenv()
# llm = OpenAI(temperature=0.9, model='gpt-3.5-turbo-16k')
# llm = HuggingFaceHub(repo_id="gpt2-xl", model_kwargs={"temperature": 0.9, "max_length":500, "min_length":500})

llm = ChatOpenAI(temperature=1, model='gpt-3.5-turbo-16k')

messages = []

# Go through the following mentioned information about a research paper and provide a 100-150 word summary of it :

text = '''
Write a concise 700 word summary of the research paper mentioned below:

Title: Sentiment analysis on social media for stock movement prediction
Author: Thien Hai Nguyen
The goal of this research is to build a model to predict stock price movement using the sentiment from social media. Unlike previous approaches where the overall moods or sentiments are considered, the sentiments of the specific topics of the company are incorporated into the stock prediction model. Topics and related sentiments are automatically extracted from the texts in a message board by using our proposed method as well as existing topic models. In addition, this paper shows an evaluation of the effectiveness of the sentiment analysis in the stock prediction task via a large scale experiment. Comparing the accuracy average over 18 stocks in one year transaction, our method achieved 2.07% better performance than the model using historical prices only. Furthermore, when comparing the methods only for the stocks that are difficult to predict, our method achieved 9.83% better accuracy than historical price method, and 3.03% better than human sentiment method.
The results of accuracy measure are shown in Table 6. In addition to the result of each stock, we also calculated the average of 18 stocks for each model for easy comparison. Using Aspect-based sentiment feature achieved the best result with 54.41% average accuracy for 18 stocks. As discussed in Section 2, degrees of accuracy of 56% hit rate are often reported as satisfying results for stock prediction. In addi- tion, the number of instances (transaction dates) in test set of most of other researches is small, and the number of stock is usually only one. In contrast, the advantage of this work is that we used the training and test data on a long period (one year) containing many instances, and for many stocks (18 stocks). For some stocks, the accuracies are quite high, such as 71.05% for AMZN stock, 64.47% for DELL stock and so on.
To assess the effectiveness of integrating mood information, we compare our Aspect-based sentiment method with the Price only method. The results show that the model using mood information outperforms 2.07% on the average accuracy than the model without mood. Furthermore, comparing the Human sentiment with Price only method, it indicated that the prediction accuracy is improved 1.91% by using the sentiments annotated by human. Therefore, we can conclude that integration of the sentiments of both overall documents and specific topics from social media could help to improve the stock market prediction. To assess the effectiveness of automatic sentiment analysis and human sentiment, we compare our Aspect-based sentiment method with the Human sentiment method. The results show that our auto- matically extracted sentiment is slightly higher than using the sentiment annotated by human. Therefore, our method is comparable to the human sentiment method. Note that the advantage of our method is that it can be applicable for other social media without human an- notated sentiment such as the Twitter.
The Aspect-based sentiment method outperformed over 2.54%, 2.14% and 2.87% on average accuracy compared to Sentiment classification, LDA-based method and JST-based method, respectively. The LDA-based and JST-based method seem to be not successful in this experiment. The limitation of these methods is that we have to specify the number of hidden topics in LDA and the number of hidden topics and sentiments in JST. In our experiment, we
specify 50 topics for all of the stock. This assumption would be not appropriate in gen- eral. For the individual stock, the number of discussed topics depends on the content of the messages. Therefore, the appropriate number of hidden topics may be varied for different stocks. However, there is no way to determine the number of topics in the model of LDA and JST. One of the solutions is a grid search trying different number of top- ics and finding the best value. However, since the running time of the Gibbs Sampling depends on the size of the dataset, it takes very long time to run it repeatedly on a big dataset of 18 stocks for a long period. Therefore, a grid search cannot be tested in our experiment.
To assess the effectiveness of topic-sentiment feature, we compare our Aspect-based sentiment method with Sentiment classification method (using only sentiment information) and LDA- based method (using only topic information). The results indicate that using topic-sentiment feature is better than using only senti- ments by 2.54% accuracy, and using only topics by 2.14% accuracy. Therefore, understanding on which topics the sentiments are ex- pressed is useful for stock market prediction. In other words, the topic-sentiment feature is better than only topic or sentiment feature. Although the sentiment information is effective for the stock pre- diction on average, in the comparison on the individual stocks, the model with sentiment analysis is worse than the price only model for several stocks. There are many possible reasons for it. As discussed in Section 2, the stock market is influenced by many factors. Some proposed that they are not predictable with more than 50% accuracy. One reason is that the sentiment might not be a factor which causes the stock price moving. Another reason is that even though sentiment might be one of the factors which affect price moving, the extracted sentiments from the Message Boards do not reflect the price because of the messy, fault comment or fault prediction of human when they post the messages.
A simple assumption about the effectiveness of sentiment feature is that the sentiment analysis may not provide any additional information if the stock movement can be predicted well by the historical price only. If the accuracy of the price only model is high, there are trends and historical repetition in the stock. In such cases, only historical prices might be enough to predict, and integration of the sentiment may not improve the accuracy much. On the other hand, if the accuracy of the price only model is low, the stock seems to have no pattern in its history. For such stocks, the use of sentiment may be effective for the prediction.
To investigate the above assumption, we compare the models from another point of view. First, we define a threshold α. If the accuracy of the stock in the Price only method (APriceOnly) is higher than α, this stock is discarded from the evaluation. In other words, we compared the average accuracy for the stocks where APriceOnly shows the average accuracies against various thresholds. It is found that the difference between the models with and without sentiment information becomes greater when α is set smaller. At the threshold 50%, using our Aspect-based sentiment model improved the accuracy over 9.83% compared to Price only, over 3.03% compared to Human sentiment method. In addition, in most of the thresholds, our method achieved the best accuracy compared with other methods.
Stock price prediction is a challenging task because the stock prices are affected by many factors. This paper presents the novel method to integrate the sentiments in social media for the predic- tion of stock price movement. The contribution of this study can be summarized as follows. First, while the overall sentiments in the doc- uments are considered in the previous research, this research pro- posed a method using the sentiment of the topic for stock market prediction. Second, we proposed two methods to capture these topic sentiment associations. One is JST-based method that relies on the existing topic model, the other is Aspect-based sentiment method where the topics and sentiments are identified by the proposed method. Finally, this is the first research to show the effectiveness of incorporation of the sentiment analysis by investigation on a large scale test data. From a practical point of view, although the average accuracy is only 54.41%, the proposed method can predict the stock price movement with more than 60% accuracy for a few stocks, and performs much better than other methods for the stocks that are difficult to predict with only past prices.
A limitation of this research is that we specified the number of topics and sentiment beforehand for the LDA and JST-based method. To overcome this weakness, a non-parametric topic model that can infer the number of topics and sentiments automatically is useful to extract the topic and sentiment simultaneously for the stock prediction. This will be done in our future work. The current model only predicts if the stock price is up or down. However, people may want to forecast drastic movement of the stock market. In that sense, the proposed model is insufficient. However, our model can be extended to predict the degree of the change by setting more fine grained classes such as 'great up', 'little up', 'little down', 'great down' and so on.
One of the weaknesses of our method is that only the historical prices and sentiments derived from social media are considered. In future, we will try to find and integrate more factors which can affect the stock prices to develop a more accurate stock prediction model. For example, co-variance between stocks, macroeconomic indicators and the financial conditions of the company, which can be guessed from the income statement, balance sheet and cash flow, are important factors to be considered in the stock prediction model.
'''

messages.append(HumanMessage(content=text))

print(llm(messages))
